---
# tasks file for local_repo

- name: Copy repo config file
  copy:
    src: dvd.repo
    dest: /etc/yum.repos.d/dvd.repo

- name: Create Mount point
  file:
    path: /mnt/dvd
    state: directory
    mode: 0755

- name: Mount DVD read-only
  mount:
    path: /mnt/dvd
    src: /dev/sr0
    fstype: iso9660
    opts: ro
    state: mounted
